// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Password struct {
	ID          int64  `json:"id"`
	AppName     string `json:"app_name"`
	AppPassword string `json:"app_password"`
	UserID      int64  `json:"user_id"`
}

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
